/** Responsive WebP variants generated by scripts/optimize-images.mjs. */
export const webp = (src: string, width: number) => src.replace(/\.jpg$/, `-${width}.webp`);

export const srcset = (src: string) => `${webp(src, 600)} 600w, ${webp(src, 1400)} 1400w`;
